obstacle_range: 2.5
raytrace_range: 3.0
transform_tolerance : 1.0
footprint: [[0.2,0.3], [0.2,-0.3],[-0.2,-0.3],[-0.2,0.3]]
#robot_radius: ir_of_robot
inflation_radius: 0.65


observation_sources: laser_scan_sensor #, point_cloud_sensor

laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true}

# point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}